[package]
name = "ncmdump"
version = "0.2.0"
authors = ["iqiziqi <iqiziqi@outlook.com>"]
edition = "2021"

description = "Netease cloud music copyright protection file dump."
homepage = "https://github.com/iqiziqi/ncmdump.rs"
documentation = "https://docs.rs/ncmdump"
repository = "https://github.com/iqiziqi/ncmdump.rs"
license = "MIT"
readme = "README.md"
keywords = ["ncm", "music"]
exclude = [
    ".editorconfig",
    ".github/**/*",
    "*.ncm"
]

[dependencies]
aes = "0.8.1"
anyhow = "1.0.57"
base64 = "0.20.0-alpha.1"
cipher = { version = "0.4.3", features = ["alloc", "block-padding"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
structopt = "0.3.2"
thiserror = "1.0.31"
