[package]
name = "ncmdump"
version = "0.1.0"
authors = ["iqiziqi <iqiziqi@outlook.com>"]
edition = "2018"

description = "Netease cloud music copyright protection file dump."
homepage = "https://github.com/haiyoune7/ncmdump.rs"
documentation = "https://docs.rs/ncmdump"
repository = "https://github.com/haiyoune7/ncmdump.rs"
license = "MIT"
readme = "README.md"
keywords = ["ncm", "music"]
exclude = [
    ".editorconfig",
    ".github/**/*",
    "*.ncm"
]

[dependencies]
aes = "0.3.2"
aes-soft = "0.3.3"
anyhow = "1.0.57"
block-modes = "0.3.3"
base64 = "0.10.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
structopt = "0.3.2"
