[package]
name = "ncmdump"
version = "0.1.0"
authors = ["haiyoune7 <haiyoune7@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
